POST http://planfix.maximsh.leads/tickets/planfix/add-new-message?hash=24ccacc7befb8dac947c66ab615b8529
Accept: application/json
Content-Type: application/json

{
  "type": "leads",
  "message_json": "{\"id\": \"123\"}"
}

###