<?php

return [
    'affiliateUserMap' => [
        'template' => ['::getTemplate' => 'user'],
        'name' => ['$first_name'],
        'lastName' => ['$last_name'],
        'post' => null,
        'email' => ['$email'],
        'mobilePhone' => ['$phone'],
        'workPhone' => null,
        'homePhone' => null,
        'address' => ['$address1', ' ', '$address2'],
        'description' => null,
        'sex' => null,
        'skype' => ['$skype'],
        'icq' => ['$icq'],
        'birthdate' => ['$birthday'],
        'lang' => 'Ru',
        'isCompany' => false,
        'canBeWorker' => true,
        'canBeClient' => true,
        'group' => ['::getGroup' => 'WEBMASTER'],
        'customData' => ['::prepareCustomStandard' => 'customContactMap'],
        'userPic' => ['$photo'],
        'havePlanfixAccess' => false,
        'contractors' => null
    ],
    'advertiserUserMap' => [
        'template' => ['::getTemplate' => 'user'],
        'name' => ['$first_name'],
        'lastName' => ['$last_name'],
        'post' => ['$post'],
        'email' => ['$email'],
        'mobilePhone' => ['$phone'],
        'workPhone' => null,
        'homePhone' => null,
        'address' => ['$address1', ' ', '$address2'],
        'description' => null,
        'sex' => null,
        'skype' => ['$skype'],
        'icq' => ['$icq'],
        'birthdate' => ['$birthday'],
        'lang' => 'Ru',
        'isCompany' => false,
        'canBeWorker' => true,
        'canBeClient' => true,
        'group' => ['::getGroup' => 'ADVERTISER'],
        'customData' => ['::prepareCustomStandard' => []],
        'userPic' => ['$photo'],
        'havePlanfixAccess' => false,
        'contractors' => null
    ],
    'advertiserCompanyMap' => [
        'template' => ['::getTemplate' => 'company'],
        'name' => ['::getNamePrefix' => null, ', ', '$company'],
        'lastName' => null,
        'mobilePhone' => ['$phone'],
        'workPhone' => null,
        'homePhone' => null,
        'address' => ['$address1', ' ', '$address2'],
        'description' => null,
        'sex' => null,
        'skype' => ['$skype'],
        'icq' => ['$icq'],
        'birthdate' => ['$birthday'],
        'lang' => 'Ru',
        'isCompany' => true,
        'canBeWorker' => true,
        'canBeClient' => true,
        'group' => ['::getGroup' => 'ADVERTISER'],
        'customData' => ['::prepareCustomStandard' => 'customContactMap'],
        'userPic' => null,
        'havePlanfixAccess' => false,
        'contractors' => null
    ],
    'affiliateCompanyMap' => [
        'template' => ['::getTemplate' => 'company'],
        'name' => ['::getNamePrefix' => null, ', ', '$company'],
        'email' => ['::getGeneratedEmail' => []],
        'lastName' => null,
        'mobilePhone' => ['$phone'],
        'workPhone' => null,
        'homePhone' => null,
        'address' => ['$address1', ' ', '$address2'],
        'description' => null,
        'sex' => null,
        'skype' => ['$skype'],
        'icq' => ['$icq'],
        'birthdate' => ['$birthday'],
        'lang' => 'Ru',
        'isCompany' => true,
        'canBeWorker' => true,
        'canBeClient' => true,
        'group' => ['::getGroup' => 'WEBMASTER'],
        'customData' => ['::prepareCustomStandard' => []],
        'userPic' => null,
        'havePlanfixAccess' => false,
        'contractors' => null
    ],
    'taskChatMap' => [
        'title' => ['::getChatTitle' => []],
        'description' => null,
        'importance' => 'AVERAGE',
        'status' => 'COMPLETED',
        'statusSet' => null,
        'checkResult' => false,
        'owner' => ['::getOwner' => ''],
        'parent' => null,
        'project' => ['::getChatProject' => []],
        'client' => ['::getChatClient' => []],
        'beginDateTime' => ['::getCreated' => 'd-m-Y H:i:s'],
        'startDateIsSet' => ['::getStartDateIsSet' => null],
        'startDate' => ['::getStartDate' => 'd-m-Y'],
        'startTimeIsSet' => ['::getStartDateIsSet' => null],
        'startTime' => ['::getStartDate' => 'H:i:s'],
        'endDateIsSet' => ['::getEndDateIsSet' => null],
        'endDate' => ['::getEndDate' => 'd-m-Y'],
        'endTimeIsSet' => ['::getEndDateIsSet' => null],
        'endTime' => ['::getEndDate' => 'H:i:s'],
        'workers' => ['::getMembers' => 'array'],
        'members' => ['::getMembers' => 'array'],
        'auditors' => ['::getMembers' => 'array'],
        'customData' => ['::prepareCustomStandard' => 'customChatMap'],
    ],
    'projectOfferMap' => [
        'title' => ['::getProjectOfferTitle' => '%s%d, %s'],
        'description' => ['$description'],
        'owner' => ['::getOwner' => ''],
        'client' => ['::getClient' => ''],
        'status' => ['::getProjectStatus' => null],
        'hidden' => false,
        'hasEndDate' => false,
        'endDate' => null,
        'group' => ['::getProjectGroup' => 'offers'],
        'parent' => ['::getParent' => null],
        'auditors' => ['::getOwner' => ''],
        'managers' => ['::getOwner' => ''],
        'workers' => ['::getOwner' => ''],
        'customData' => ['::prepareCustomStandard' => 'customProjectMap'],
    ],
    'taskOfferMap' => [
        'template' => ['::getTemplate' => 'offerTask'],
        'title' => ['::getTitle' => 'Новый домен %s, оффер: %d, %s'],
        'description' => ['::getDescription' => null],
        'importance' => 'AVERAGE',
        'status' => ['::getStatus' => null],
        'statusSet' => null,
        'checkResult' => false,
        'owner' => null,
        'parent' => null,
        'project' => ['::getProject' => []],
        'client' => ['::getClient' => []],
        'beginDateTime' => null,
        'startDateIsSet' => null,
        'startDate' => null,
        'startTimeIsSet' => null,
        'startTime' => null,
        'endDateIsSet' => null,
        'endDate' => null,
        'endTimeIsSet' => null,
        'endTime' => null,
        'workers' => ['::getWorkers' => 'array'],
        'members' => ['::getWorkers' => 'array'],
        'auditors' => null,
        'customData' => ['::prepareCustomStandard' => 'customTaskOfferMap'],
    ],
    'taskTicketMap' => [
        'template' => ['::getTicketTemplate' => null],
        'title' => [
            '::getTicketTaskTitle' => '%d, %s.'
        ],
        'description' => [
            '::getTicketTaskDescription' =>
                implode('',
                    [
                        '<b>Описание тикета:</b><br> %s',
                        '<b>Данные тикета:</b><br> %s',
                        '<b>Данные агентского кабинета:</b><br> %s',
                        '<b>Ссылка на тикет в ЛКМ:</b><br> %s'
                    ])
        ],
        'status' => ['::getStatus' => null],
        'statusSet' => null,
        'checkResult' => true,
        'owner' => ['::getTicketClient' => 'id'],
        'parent' => null,
        'client' => ['::getTicketClient' => 'id'],
        'beginDateTime' => ['::getCreated' => 'd-m-Y H:i:s'],
        'startDateIsSet' => ['::getStartDateIsSet' => null],
        'startDate' => ['::getCreated' => 'd-m-Y'],
        'startTimeIsSet' => ['::getStartDateIsSet' => null],
        'startTime' => ['::getCreated' => 'H:i:s'],
        'endDateIsSet' => false,
        'endTimeIsSet' => false,
        'customData' => ['::prepareCustomStandard' => 'customTicketMap'],
    ],
    'taskBonusMap' => [
        'template' => ['::getTemplate' => 'bonusTask'],
        'title' => ['::getTitle' => '%s %s, %s (%s)'],
        'description' => ['::getDescription' => null],
        'importance' => 'AVERAGE',
        'status' => 'ACTIVE',
        'statusSet' => null,
        'checkResult' => false,
        'owner' => ['::getClient' => 'planfix_userid'],
        'parent' => null,
        'project' => null,
        'client' => ['::getClient' => 'planfix_id'],
        'beginDateTime' => null,
        'startDateIsSet' => null,
        'startDate' => null,
        'startTimeIsSet' => null,
        'startTime' => null,
        'endDateIsSet' => null,
        'endDate' => null,
        'endTimeIsSet' => null,
        'endTime' => null,
        'workers' => ['::getWorkers' => 'array'],
        'members' => ['::getWorkers' => 'array'],
        'auditors' => null,
        'customData' => ['::prepareCustomStandard' => 'customTaskBonusMap'],
    ],
    'taskOfferStatusMap' => [
        'template' => ['::getTemplate' => 'offerTask'],
        'title' => ['::getTitle' => 'Новый домен %s, оффер: %d, %s'],
        'description' => ['::getDescription' => null],
        'status' => ['::getStatus' => null],
        'statusSet' => null,
        'customData' => ['::prepareCustomStandard' => 'customTaskOfferMap'],
        'workers' => ['::getWorkers' => 'array'],
        'members' => ['::getWorkers' => 'array'],

    ],
    'customContactMap' => [
        'modified' => ['::getDateModified' => null],
        'date_create' => ['::getDateAdded' => null],
        'network' => ['::getNetworks' => []],
        'status' => ['::getRuStatus' => null],
        'cabinetOwner' => ['::getCabinetOwnerString' => '%s, <%s>']
    ],
    'customChatMap' => [

    ],
    'customPayoutMap' => [

    ],
    'customTicketMap' => [
        'ticketAccountType' => ['::getAccountType' => null],
        'ticketAccountId' => ['::getAccountId' => null],
        'ticketCategoryName' => ['::getTicketCategoryName' => null],
        'ticketSubCategoryName' => ['::getTicketSubCategoryName' => null],
    ],
    'customProjectMap' => [
        'projectNetwork' => ['::getProjectNetwork' => []],
        'cabinetUrl' => ['::getCabinetOfferUrl' => 'manager'],
        'offerStatus' => ['::getCabinetOfferStatus' => null],
    ],
    'customTaskOfferMap' => [

    ],
    'customTaskBonusMap' => [
        'totalSum' => ['::getAchieveAmount' => null],
        'achieveType' => ['::getAchieveType' => null],
        'cabinetId' => ['::getId' => null],
    ],
    'statusMap' => [
        'active' => 'Активный',
        'blocked' => 'Заблокированый'
    ],
    'actionChatMap' => [
        'description' => ['::getMessageContent' => ''],
        'taskNewStatus' => false,
        'task' => ['::getActionTaskId' => ''],
        'notifiedList' => 0,
        'isHidden' => 0,
        'owner' => ['::getActionWorkers' => ''],
        'dateTime' => ['::getCreated' => 'd-m-Y H:i:s'],
    ],
    'actionContactMap' => [
        'taskNewStatus' => false,
        'description' => ['::getNoteDescription' => ''],
        'task' => ['::getNoteContactId' => ''],
        'notifiedList' => 0,
        'isHidden' => 0,
        'owner' => ['::getNoteOwner' => ''],
        'dateTime' => ['::getCreated' => 'd-m-Y H:i:s'],
    ],
    'taskPayoutMap' => [
        'template' => ['::getPayoutTemplate' => 'taskPayout'],
        'title' => [
            '::getPayoutTaskTitle' => 'Срочная выплата. %d р., комиссия: %s, %s, %s.'
        ],
        'description' => [
            '::getPayoutTaskDescription' => 'Сумма выплаты: <b>%d р.</b><br>Комиссия: <b>%s</b><br>Комментарий вебмастера: <b>%s</b><br>Вы должны проверить трафик вебмастера и разрешить или отклонить выплату'
        ],
        'importance' => 'HIGH',
        'status' => 'ACTIVE',
        'statusSet' => null,
        'checkResult' => true,
        'owner' => ['::getPayoutClient' => 'userid'],
        'parent' => null,
        'project' => ['::getPayoutProject' => 'fastPayments'],
        'client' => ['::getPayoutClient' => 'id'],
        'beginDateTime' => ['::getCreated' => 'd-m-Y H:i:s'],
        'startDateIsSet' => ['::getStartDateIsSet' => null],
        'startDate' => ['::getCreated' => 'd-m-Y'],
        'startTimeIsSet' => ['::getStartDateIsSet' => null],
        'startTime' => ['::getCreated' => 'H:i:s'],
        'endDateIsSet' => false,
        'endTimeIsSet' => false,
        'workers' => ['::getWorkers' => null],
        'members' => ['::getWorkers' => null],
        'customData' => ['::prepareCustomStandard' => 'customPayoutMap'],
    ],
];
