#!/bin/sh

if [ -n "$app_config" -a "$app_config" != "development" ];
then
    yii_app='/home/app/www/yii'
else
    yii_app='/home/app/planfix/www/yii'
fi
current_date_time="`date +%Y%m%d%H%M%S`";
$yii_app sync-base/dump-notifications automatic_backup_$current_date_time